### ISSUE TITLE
New setup - Prefix not working

### ISSUE THREAD

**Issue by faceslog** [Servatom/Notion-DiscordBot#88]
Hi, 

First of all thanks for your hard work. However I recently updated my docker image and since then it has been really hard to run the bot, (old docker compose below).
I just saw there is a new `setup` command that can be run from discord, so I guess no need to use `DATABASE_TOKEN` and `AUTH_KEY` as environment variables anymore. So I removed them from my docker compose and then the annoying stuff happened. Every time I restart my container I have to run the `setup` command, the prefix does not work I have to use `*` everywhere instead of `!`. ( See screen attached below). I would personally prefer the notion's integration app as environment variable that is probably more secure than discord. Maybe in the future it could be prompted only when the user does not provide it as env 🤷‍♂️.

Thanks for your time, and hope you will be able to fix those issues and update the README file.

Regards

```
---
version: "3.4"

services:
  notiondiscordbot:
    image: servatom/notiondiscordbot
    container_name: notiondiscordbot
    restart: unless-stopped
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=Europe/Paris
      - DATABASE_TOKEN=...  # Can be removed
      - AUTH_KEY=...               # Can be removed
      - DISCORD_AUTH=...      # Need to be change to TOKEN
      - GDRIVE_FOLDER=...
      - PREFIX=!
    volumes:
      - /user/docker/notion-data:/Bot/creds
    security_opt:
      - no-new-privileges:true
```

<img src="https://i.imgur.com/EnI29IG.png" alt="prefix-bug" />
